version: '3.8'

services:
  postgresdb:
    build: './database'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    restart: always

# Based on nats image
  nats:
    image: "nats-streaming:0.9.2"
    restart: always